Automation code for the testcase "Add Job Title"
AjuramKSalim/oramgehrm-batch27 pull request #5
Opened 2023-02-05 14:11 UTC by Neethujn

testcase for add job

2023-02-05 14:36 UTC, RahulNair92 requested changes

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/LoginTests.java
> +
This needs to be changed as it was

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/JobTitleTest.java
> +
remove blank lines

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/JobTitleTest.java
> +       // String uuid = UUID.randomUUID().toString();
String uuid = UUID.randomUUID().toString();
 String jobname= "JobTitle Test " + uuid;
 jobPage.saveNewJob(jobname);

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/JobTitleTest.java
> +        jobPage.saveNewJob("Quality Engineer");
rename method from saveNewJob to saveJobAndVerifyDisplayed

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/pages/JobTitlePage.java
> +    private final String idJobAddBtn = ".oxd-button--secondary";
remove text id from variable name as it is confusing
remove blank lines

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/pages/JobTitlePage.java
> +    //private final String educations = "//div[@class='oxd-table-body'] /div[@class='oxd-table-card']";
remove comments

2023-02-05 14:36 UTC, RahulNair92 commented on src/test/java/ca/qaguru/oranghrmbatch27/pages/EducationPage.java
> +    // //div[contains(@class, 'oxd-table-body')]/div[contains(@class,'oxd-table-card')]
you need to revert

2023-02-05 14:36 UTC, RahulNair92 commented on pom.xml
> -                     </suiteXmlFiles>
revert this back

2023-02-05 14:40 UTC, Neethujn commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/LoginTests.java
> +
done with the changes

2023-02-05 14:40 UTC, Neethujn commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/JobTitleTest.java
> +
removed the blank lines

2023-02-05 17:30 UTC, Neethujn commented on src/test/java/ca/qaguru/oranghrmbatch27/tests/JobTitleTest.java
> +       // String uuid = UUID.randomUUID().toString();
done

2023-02-05 17:30 UTC, Neethujn commented on src/test/java/ca/qaguru/oranghrmbatch27/pages/JobTitlePage.java
> +    //private final String educations = "//div[@class='oxd-table-body'] /div[@class='oxd-table-card']";
removed

2023-02-05 17:30 UTC, Neethujn commented on src/test/java/ca/qaguru/oranghrmbatch27/pages/EducationPage.java
> +    // //div[contains(@class, 'oxd-table-body')]/div[contains(@class,'oxd-table-card')]
reverted the changes

2023-02-12 15:24 UTC, RahulNair92 approved these changes

2023-02-12 15:25 UTC, merged